# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.REPLACEMENTMARKER-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b3a549c5492ef3bb23b828d1dad7f2fce2888bd510600932c9a79724f718d2f3_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.REPLACEMENTMARKER-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b3a549c5492ef3bb23b828d1dad7f2fce2888bd510600932c9a79724f718d2f3_sk -b admin:etherMoneyVapor1024 -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.REPLACEMENTMARKER/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.REPLACEMENTMARKER-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6c9b9b4528f72860e834b44aadd0b14c4ac5a69d19482bce0d094c7e8ab7cb6f_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.REPLACEMENTMARKER-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6c9b9b4528f72860e834b44aadd0b14c4ac5a69d19482bce0d094c7e8ab7cb6f_sk -b admin:etherMoneyVapor1024 -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.REPLACEMENTMARKER/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn
